export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const SEARCH_PRODUCTS = "SEARCH_PRODUCTS";
export const EMPTY_USER = "EMPTY_USER";
export const RECEIVE_USER = "RECEIVE_USER";
export const SELECT_PRODUCT = "SELECT_PRODUCT";
export const FILTER_PRODUCT = "FILTER_PRODUCT";
export const ADD_TO_CART = "ADD_TO_CART";
export const DELETE_TO_CART = "DELETE_TO_CART";
